version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
      - storage:/var/www/html/storage
      - vendor:/var/www/html/vendor
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      LOG_CHANNEL: stack
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: secret123
    depends_on:
      - db
    networks:
      - laravel-net

  db:
    image: mariadb:10.9
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret123
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-net

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - laravel-net

volumes:
  storage:
  vendor:
  dbdata:

networks:
  laravel-net:
    driver: bridge
