### Listar todos os produtos
GET http://localhost/api/products
Accept: application/json

### Criar novo produto
POST http://localhost/api/products
Content-Type: application/json

{
  "name": "Produto Exemplo",
  "price": 99.90,
  "stock": 100
}

### Buscar produto pelo ID
GET http://localhost/api/products/1
Accept: application/json

### Atualizar produto
PUT http://localhost/api/products/1
Content-Type: application/json

{
  "name": "Produto Atualizado",
  "price": 120.50
}

### Deletar produto
DELETE http://localhost/api/products/1
Accept: application/json
